import type { Finding, Scan, Recommendation } from "@/lib/types";

export const MOCK_SCANS: Scan[] = [
  {
    id: "scan_8f21",
    name: "payments-service (main)",
    inputType: "SOURCE_REPOSITORY",
    sourceLabel: "git@github.com:acme/payments-service.git",
    status: "COMPLETED",
    progressPercent: 100,
    createdAt: "2026-09-08T09:12:00Z",
    startedAt: "2026-09-08T09:12:05Z",
    completedAt: "2026-09-08T09:14:41Z",
    requestedBy: "a.iyer",
    findingCount: 42,
    highRiskCount: 9,
    coverage: {
      filesScanned: 1284,
      filesTotal: 1310,
      unsupportedFiles: 26,
      parseErrors: 3,
      warnings: [
        { code: "UNSUPPORTED_EXT", message: "26 files with unsupported extensions were skipped." },
        { code: "PARSE_ERROR", message: "Failed to parse minified bundle.", path: "dist/vendor.min.js" }
      ]
    }
  },
  {
    id: "scan_3b77",
    name: "auth-gateway container image",
    inputType: "CONTAINER_IMAGE",
    sourceLabel: "registry.acme.internal/auth-gateway:2.14.0",
    status: "ASSESSING_RISK",
    progressPercent: 72,
    createdAt: "2026-09-11T14:02:00Z",
    startedAt: "2026-09-11T14:02:10Z",
    requestedBy: "s.rao",
    coverage: {
      filesScanned: 640,
      filesTotal: 900,
      unsupportedFiles: 4,
      parseErrors: 0,
      warnings: []
    }
  },
  {
    id: "scan_c110",
    name: "legacy-billing.jar",
    inputType: "BINARY_LIBRARY",
    sourceLabel: "legacy-billing-4.2.1.jar",
    status: "FAILED",
    progressPercent: 34,
    createdAt: "2026-09-10T11:40:00Z",
    startedAt: "2026-09-10T11:40:08Z",
    completedAt: "2026-09-10T11:41:02Z",
    requestedBy: "s.rao",
    errorMessage: "Binary is obfuscated; symbol extraction failed after 3 retries.",
    coverage: {
      filesScanned: 12,
      filesTotal: 58,
      unsupportedFiles: 40,
      parseErrors: 6,
      warnings: [{ code: "OBFUSCATED_BINARY", message: "Class files appear obfuscated; static analysis coverage is limited." }]
    }
  },
  {
    id: "scan_a904",
    name: "edge-tls-certs",
    inputType: "CERTIFICATE",
    sourceLabel: "certs/edge/*.pem (18 files)",
    status: "COMPLETED",
    progressPercent: 100,
    createdAt: "2026-09-09T08:00:00Z",
    startedAt: "2026-09-09T08:00:04Z",
    completedAt: "2026-09-09T08:01:12Z",
    requestedBy: "a.iyer",
    findingCount: 18,
    highRiskCount: 2,
    coverage: { filesScanned: 18, filesTotal: 18, unsupportedFiles: 0, parseErrors: 0, warnings: [] }
  },
  {
    id: "scan_e551",
    name: "inventory-service deps",
    inputType: "DEPENDENCY_MANIFEST",
    sourceLabel: "pom.xml + package-lock.json",
    status: "QUEUED",
    progressPercent: 0,
    createdAt: "2026-09-12T06:20:00Z",
    requestedBy: "d.chen"
  }
];

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "f_0001",
    scanId: "scan_8f21",
    assetType: "SOURCE_REPOSITORY",
    algorithm: "RSA",
    variant: "PKCS#1 v1.5",
    primitiveType: "KEY_EXCHANGE",
    keySize: 2048,
    library: "node-forge",
    libraryVersion: "1.3.1",
    sourcePath: "src/services/payment-auth.ts",
    lineStart: 88,
    lineEnd: 96,
    inputType: "SOURCE_REPOSITORY",
    detectionMethods: ["STATIC_AST", "API_CALL_SIGNATURE"],
    evidence: "forge.pki.rsa.generateKeyPair({ bits: 2048 })",
    confidence: "HIGH",
    classicalStatus: "SAFE",
    quantumStatus: "BROKEN",
    dataLifetime: "LONG",
    businessCriticality: "CRITICAL",
    migrationTime: "HIGH",
    riskLevel: "HIGH",
    riskScore: 78,
    riskExplanation:
      "RSA-2048 key establishment is classically adequate today but is fully broken by a cryptographically relevant quantum computer (Shor's algorithm). Payment session keys are long-lived and business-critical, which raises priority despite no current classical weakness.",
    isAssumption: { dataLifetime: true, businessCriticality: false },
    recommendation: {
      id: "r_0001",
      findingId: "f_0001",
      currentTechnology: "RSA-2048 key transport",
      affectedComponents: ["payments-service", "payment-auth module"],
      reason: "Key establishment using RSA is vulnerable to future quantum attack; harvest-now-decrypt-later risk applies given long data lifetime.",
      direction: "HYBRID_KEM",
      candidateAlgorithm: "X25519 + ML-KEM-768 (hybrid)",
      priority: "HIGH",
      status: "NOT_STARTED",
      rationale: "Hybrid KEM preserves classical security guarantees while adding post-quantum protection during the transition period.",
      effort: "HIGH",
      tradeOffs: "Larger handshake payloads; requires library upgrade and interop testing with downstream partners."
    }
  },
  {
    id: "f_0002",
    scanId: "scan_8f21",
    assetType: "SOURCE_REPOSITORY",
    algorithm: "AES",
    variant: "AES-GCM",
    primitiveType: "SYMMETRIC_CIPHER",
    keySize: 256,
    mode: "GCM",
    library: "node:crypto",
    libraryVersion: "builtin",
    sourcePath: "src/services/token-vault.ts",
    lineStart: 41,
    lineEnd: 47,
    inputType: "SOURCE_REPOSITORY",
    detectionMethods: ["STATIC_AST"],
    evidence: "crypto.createCipheriv('aes-256-gcm', key, iv)",
    confidence: "HIGH",
    classicalStatus: "SAFE",
    quantumStatus: "WEAK",
    dataLifetime: "MEDIUM",
    businessCriticality: "HIGH",
    migrationTime: "LOW",
    riskLevel: "LOW",
    riskScore: 22,
    riskExplanation:
      "AES-256-GCM retains roughly 128 bits of security under Grover's algorithm, which is considered adequate. No action required beyond continued key-size monitoring.",
    recommendation: {
      id: "r_0002",
      findingId: "f_0002",
      currentTechnology: "AES-256-GCM",
      affectedComponents: ["payments-service", "token-vault module"],
      reason: "Already meets post-quantum symmetric security guidance; retained for completeness.",
      direction: "NO_ACTION",
      candidateAlgorithm: "AES-256-GCM (unchanged)",
      priority: "LOW",
      status: "ACCEPTED_RISK",
      rationale: "Symmetric strength is sufficient against known quantum attacks at this key size."
    }
  },
  {
    id: "f_0003",
    scanId: "scan_8f21",
    assetType: "SOURCE_REPOSITORY",
    algorithm: "MD5",
    primitiveType: "HASH",
    library: "node:crypto",
    libraryVersion: "builtin",
    sourcePath: "src/legacy/checksum.ts",
    lineStart: 12,
    lineEnd: 14,
    inputType: "SOURCE_REPOSITORY",
    detectionMethods: ["STATIC_AST"],
    evidence: "crypto.createHash('md5')",
    confidence: "HIGH",
    classicalStatus: "BROKEN",
    quantumStatus: "BROKEN",
    dataLifetime: "SHORT",
    businessCriticality: "LOW",
    migrationTime: "LOW",
    riskLevel: "CRITICAL",
    riskScore: 93,
    riskExplanation:
      "MD5 has practical collision attacks today, independent of any quantum consideration. Used here for a checksum, but any integrity-relevant use of MD5 should be treated as broken.",
    recommendation: {
      id: "r_0003",
      findingId: "f_0003",
      currentTechnology: "MD5",
      affectedComponents: ["payments-service", "legacy checksum utility"],
      reason: "MD5 has known practical collision attacks and must not be relied on for integrity.",
      direction: "APPROVED_HASH",
      candidateAlgorithm: "SHA-256 (or SHA-3-256)",
      priority: "CRITICAL",
      status: "IN_PROGRESS",
      rationale: "Direct drop-in replacement; low migration effort relative to the severity of current exposure.",
      effort: "LOW"
    }
  },
  {
    id: "f_0004",
    scanId: "scan_8f21",
    assetType: "SOURCE_REPOSITORY",
    algorithm: "ECDSA",
    variant: "secp256r1",
    primitiveType: "DIGITAL_SIGNATURE",
    keySize: 256,
    library: "node:crypto",
    libraryVersion: "builtin",
    sourcePath: "src/services/webhook-signer.ts",
    lineStart: 55,
    lineEnd: 63,
    inputType: "SOURCE_REPOSITORY",
    detectionMethods: ["STATIC_AST", "API_CALL_SIGNATURE"],
    evidence: "crypto.createSign('SHA256').sign(privateKey)",
    confidence: "MEDIUM",
    classicalStatus: "SAFE",
    quantumStatus: "BROKEN",
    dataLifetime: "MEDIUM",
    businessCriticality: "HIGH",
    migrationTime: "MEDIUM",
    riskLevel: "MEDIUM",
    riskScore: 61,
    riskExplanation:
      "ECDSA signatures are classically strong but broken by Shor's algorithm. Signature forgery only matters for the validity window of signed webhooks, which moderates urgency relative to long-lived key establishment.",
    isAssumption: { dataLifetime: true, businessCriticality: true },
    recommendation: {
      id: "r_0004",
      findingId: "f_0004",
      currentTechnology: "ECDSA (secp256r1)",
      affectedComponents: ["payments-service", "webhook-signer module"],
      reason: "Digital signature scheme is quantum-vulnerable; webhook authenticity guarantees would fail against a CRQC.",
      direction: "ML_DSA",
      candidateAlgorithm: "ML-DSA-65",
      priority: "MEDIUM",
      status: "NOT_STARTED",
      rationale: "ML-DSA is the finalized NIST signature standard appropriate for this purpose.",
      effort: "MEDIUM"
    }
  },
  {
    id: "f_0005",
    scanId: "scan_8f21",
    assetType: "SOURCE_REPOSITORY",
    algorithm: "Custom XOR cipher",
    primitiveType: "CUSTOM_UNKNOWN",
    library: "internal",
    sourcePath: "src/legacy/obfuscate.ts",
    lineStart: 3,
    lineEnd: 21,
    inputType: "SOURCE_REPOSITORY",
    detectionMethods: ["HEURISTIC_STRING_MATCH"],
    evidence: "byte[i] ^= key[i % key.length]",
    confidence: "LOW",
    classicalStatus: "BROKEN",
    quantumStatus: "BROKEN",
    dataLifetime: "Unknown",
    businessCriticality: "Unknown",
    migrationTime: "UNKNOWN",
    riskLevel: "HIGH",
    riskScore: 71,
    riskExplanation:
      "Pattern matches a hand-rolled XOR-based obfuscation routine rather than a vetted cipher. Detection confidence is low because it relies on heuristic string matching, not direct API evidence — but the risk is treated as high regardless, since custom crypto is presumed weak until manually reviewed.",
    recommendation: {
      id: "r_0005",
      findingId: "f_0005",
      currentTechnology: "Unvetted custom cipher",
      affectedComponents: ["payments-service", "legacy obfuscation utility"],
      reason: "Custom, non-standard cryptographic constructions cannot be assessed for security guarantees without manual review.",
      direction: "VETTED_STANDARD_REVIEW",
      candidateAlgorithm: "Not applicable — requires manual cryptographic review",
      priority: "HIGH",
      status: "NOT_STARTED",
      rationale: "Replace with a vetted standard construction once the intended purpose (obfuscation vs. confidentiality) is confirmed with the owning team."
    }
  },
  {
    id: "f_0006",
    scanId: "scan_a904",
    assetType: "CERTIFICATE",
    algorithm: "RSA",
    variant: "X.509",
    primitiveType: "CERTIFICATE",
    keySize: 1024,
    protocol: "TLS 1.2",
    sourcePath: "certs/edge/legacy-partner.pem",
    inputType: "CERTIFICATE",
    detectionMethods: ["CERTIFICATE_PARSE"],
    evidence: "Subject: CN=legacy-partner.acme.io, Key: rsaEncryption (1024 bit)",
    confidence: "HIGH",
    classicalStatus: "WEAK",
    quantumStatus: "BROKEN",
    dataLifetime: "LONG",
    businessCriticality: "HIGH",
    migrationTime: "MEDIUM",
    riskLevel: "CRITICAL",
    riskScore: 89,
    riskExplanation:
      "1024-bit RSA is below currently recommended key sizes and considered classically weak, in addition to being quantum-broken. This certificate secures a long-lived partner integration.",
    recommendation: {
      id: "r_0006",
      findingId: "f_0006",
      currentTechnology: "RSA-1024 X.509 certificate",
      affectedComponents: ["edge TLS termination", "legacy partner integration"],
      reason: "Key size is below current classical security recommendations, independent of quantum concerns.",
      direction: "HYBRID_KEM",
      candidateAlgorithm: "RSA-3072/ECDSA P-256 now; hybrid KEM for the TLS key exchange during renegotiation support window",
      priority: "CRITICAL",
      status: "NOT_STARTED",
      rationale: "Immediate reissue at a stronger classical key size, with a hybrid path tracked for the next certificate rotation.",
      effort: "MEDIUM"
    }
  },
  {
    id: "f_0007",
    scanId: "scan_a904",
    assetType: "CERTIFICATE",
    algorithm: "ECDSA",
    variant: "X.509",
    primitiveType: "CERTIFICATE",
    keySize: 384,
    protocol: "TLS 1.3",
    sourcePath: "certs/edge/api-gateway.pem",
    inputType: "CERTIFICATE",
    detectionMethods: ["CERTIFICATE_PARSE"],
    evidence: "Subject: CN=api.acme.io, Key: id-ecPublicKey (secp384r1)",
    confidence: "HIGH",
    classicalStatus: "SAFE",
    quantumStatus: "BROKEN",
    dataLifetime: "MEDIUM",
    businessCriticality: "CRITICAL",
    migrationTime: "MEDIUM",
    riskLevel: "MEDIUM",
    riskScore: 58,
    riskExplanation:
      "ECDSA P-384 is classically strong and currently the recommended curve size, but remains quantum-vulnerable for long-term protection.",
    recommendation: {
      id: "r_0007",
      findingId: "f_0007",
      currentTechnology: "ECDSA P-384 X.509 certificate",
      affectedComponents: ["public API gateway"],
      reason: "Signature scheme will need a post-quantum path ahead of the CRQC scenario window.",
      direction: "ML_DSA",
      candidateAlgorithm: "ML-DSA-87 (evaluate CA/browser support before adoption)",
      priority: "MEDIUM",
      status: "NOT_STARTED",
      rationale: "No immediate action required; track ecosystem support for PQC certificates.",
      isExperimental: false
    }
  },
  {
    id: "f_0008",
    scanId: "scan_3b77",
    assetType: "CONTAINER_IMAGE",
    algorithm: "SHA-1",
    primitiveType: "HASH",
    library: "openssl",
    libraryVersion: "1.1.1",
    sourcePath: "/usr/lib/x86_64-linux-gnu/libssl.so.1.1",
    inputType: "CONTAINER_IMAGE",
    detectionMethods: ["BINARY_SYMBOL"],
    evidence: "Symbol reference: SHA1_Update, SHA1_Final",
    confidence: "MEDIUM",
    classicalStatus: "WEAK",
    quantumStatus: "WEAK",
    dataLifetime: "Unknown",
    businessCriticality: "MEDIUM",
    migrationTime: "MEDIUM",
    riskLevel: "MEDIUM",
    riskScore: 54,
    riskExplanation:
      "SHA-1 has practical collision attacks in adversarial-input settings. Detected via linked binary symbols; the calling context (integrity vs. non-security use) could not be determined statically inside a container image.",
    recommendation: {
      id: "r_0008",
      findingId: "f_0008",
      currentTechnology: "SHA-1",
      affectedComponents: ["auth-gateway base image"],
      reason: "SHA-1 should not be used where collision resistance matters; confirm call sites before treating as urgent.",
      direction: "APPROVED_HASH",
      candidateAlgorithm: "SHA-256",
      priority: "MEDIUM",
      status: "NOT_STARTED",
      rationale: "Upgrade base image / OpenSSL version and confirm no security-relevant call sites remain on SHA-1."
    }
  },
  {
    id: "f_0009",
    scanId: "scan_3b77",
    assetType: "CONTAINER_IMAGE",
    algorithm: "ChaCha20-Poly1305",
    primitiveType: "SYMMETRIC_CIPHER",
    library: "libsodium",
    libraryVersion: "1.0.18",
    sourcePath: "/app/vendor/libsodium.so",
    inputType: "CONTAINER_IMAGE",
    detectionMethods: ["BINARY_SYMBOL"],
    evidence: "Symbol reference: crypto_aead_chacha20poly1305_encrypt",
    confidence: "MEDIUM",
    classicalStatus: "SAFE",
    quantumStatus: "WEAK",
    dataLifetime: "MEDIUM",
    businessCriticality: "MEDIUM",
    migrationTime: "LOW",
    riskLevel: "LOW",
    riskScore: 18,
    riskExplanation: "ChaCha20-Poly1305 at standard key size retains adequate security margin under Grover's algorithm.",
    recommendation: {
      id: "r_0009",
      findingId: "f_0009",
      currentTechnology: "ChaCha20-Poly1305",
      affectedComponents: ["auth-gateway"],
      reason: "Meets current post-quantum symmetric guidance.",
      direction: "NO_ACTION",
      candidateAlgorithm: "ChaCha20-Poly1305 (unchanged)",
      priority: "LOW",
      status: "ACCEPTED_RISK",
      rationale: "No change required."
    }
  }
];

export const MOCK_RECOMMENDATIONS: Recommendation[] = MOCK_FINDINGS.filter((f) => !!f.recommendation).map(
  (f) => f.recommendation as Recommendation
);
